version: '1'
services:
  app:
    image: minnbanya/st124145:A3
    ports:
      - "8000:8000"
    build: 
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./code:/root/code
      - ./.vscode-server:/root/.vscode-server
    command: python3 app.py